### ISSUE TITLE
Splunk / Hunk POC

### ISSUE THREAD

**Issue by MikeSwafford** [MikeSwafford/00_DataUsability#1]
Initial, rough outline: 
- [ ] CSIRT  - Contact Splunk for Hunk trial licensing
- [ ] TIP    - Send dummy data to Splunk
- [ ] Splunk - Create lookup PoC to handle anonymization, depends on #2
- [ ]  TIP    - Get dev Splunk VM
  ...
- [ ] TIP    - test lookup functionality, depends on #10
- [ ] CSIRT  - validate lookup functionality, depends on #11

**Comment by MikeSwafford** [comment]
THis is a great idea
